Add project
lukviktor/Sprint_4 pull request #1
Opened 2023-02-28 20:51 UTC by lukviktor

Add project for scooters

2023-03-02 08:57 UTC, alstafeev requested changes

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/PageObject/MainOrderPage.java
> +        TimeUnit.SECONDS.sleep(2);
Надо исправить - sleep надо удалить. Можно заменить на WebDriverWait

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/PageObject/MainOrderPage.java
> +        TimeUnit.SECONDS.sleep(1);
Надо исправить - sleep надо удалить. Можно заменить на WebDriverWait

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +            String xpathQuestion = ".//div[@id='accordion__heading-" + numberRow + "']"; // Поиск вопроса
Надо исправить - локаторы должны быть в PageObject

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +                            ".//div[@aria-labelledby='accordion__heading-" + numberRow + "']//p"))
Надо исправить - локаторы должны быть в PageObject

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +        public void QuestionsImportantDropDownListNoErrors() {
Надо исправить - название метода не по java style

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +    public void OrderingScooterPositiveScenarioUpperButtonShowsErrorChromeBrowser() throws InterruptedException {
Надо исправить - название метода не по java style

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +    public void OrderingScooterPositiveScenarioLowButtonShowsErrorChromeBrowser() throws InterruptedException {
Надо исправить - название метода не по java style

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +    public void ClickLogoScooterRedirectsMainPageNoError() {
Надо исправить - название метода не по java style

2023-03-02 08:57 UTC, alstafeev commented on src/test/java/scootertests/TestScooter.java
> +    public static class QuestionsImportant {
Надо исправить - класс QuestionsImportant, но в классе тесты не только вопросов, надо разделить по тематике

2023-03-04 04:30 UTC, closed without merging

2023-03-04 04:30 UTC, lukviktor commented
deleted all files